[project]
name = "restaurant-revenue-mlops"
version = "0.1.0"
description = "Restaurant revenue prediction MLOps project for TFI"
requires-python = ">=3.12"
dependencies = [
    "pandas==2.2.3",
    "numpy==2.2.6",
    "matplotlib==3.10.3",
    "seaborn==0.13.2",
    "ipykernel>=7.2.0",
    "pandas-stubs~=2.2.3",
    "jinja2==3.1.6",
    "scipy==1.17.1",
    "scikit-learn==1.8.0",
    "mlflow==3.12.0",
    "xgboost==3.2.0",
    "lightgbm==4.6.0",
    "dvc==3.67.1",
    "pytest==9.0.3",
    "httpx==0.28.1",
    "optuna==4.6.0",
]

[dependency-groups]
dev = [
    "kagglehub==1.0.1",
]

[tool.setuptools.packages.find]
where = ["src"]
